-- 계정 생성
CREATE USER KH_FINAL IDENTIFIED BY KH_FINAL;
GRANT RESOURCE, CONNECT, DBA TO KH_FINAL;

SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'KH_FINAL';

SELECT * FROM DBA_ROLE_PRIVS
WHERE GRANTEE = 'KH_FINAL2';

CREATE USER KH_FINAL2 IDENTIFIED BY KH_FINAL2;
DROP USER KH_FINAL2;
GRANT RESOURCE, CONNECT TO KH_FINAL2;

select * from role_sys_privs
where role='RESOURCE';

-- 이걸로 권한 주면 됨
alter user "KH_FINAL2" default tablespace users quota unlimited on users;

CREATE TABLE TEST (
    NO NUMBER
);

INSERT INTO TEST VALUES(1);