-- DDL

DROP TABLE CALENDAR2;
CREATE TABLE CALENDAR2 (
    CAL_NO NUMBER PRIMARY KEY,
    NAME VARCHAR(30),
    COLOR VARCHAR(10),
    STATUS CHAR(1) DEFAULT 'Y',
    IS_DELETE CHAR(1) DEFAULT 'N',
    EMP_NO NUMBER
);

DROP TABLE EVENT2;
CREATE TABLE EVENT2 (
    EVT_NO NUMBER PRIMARY KEY,
    NAME VARCHAR(30),
    START_DATE DATE,
    END_DATE DATE,
    IS_DELETE CHAR(1) DEFAULT 'N',
    CAL_NO NUMBER,
    REZ_NO NUMBER
);

DROP TABLE RESERVATION2;
CREATE TABLE RESERVATION2 (
    REZ_NO NUMBER PRIMARY KEY,
    NAME VARCHAR(30),
    START_DATE DATE,
    END_DATE DATE,
    IS_DELETE CHAR(1) DEFAULT 'N',
    AS_NO NUMBER,
    EVT_NO NUMBER
);

DROP TABLE ASSET2;
CREATE TABLE ASSET2 (
    AS_NO NUMBER PRIMARY KEY,
    NAME VARCHAR(30),
    COLOR VARCHAR(10),
    IS_DELETE CHAR(1) DEFAULT 'N'
);
    
-- comment, 나중에

-- sequence
CREATE SEQUENCE SEQ_CAL_ID START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_EVT_ID START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_REZ_ID START WITH 1 NOCACHE;
CREATE SEQUENCE SEQ_AS_ID START WITH 1 NOCACHE;

DROP SEQUENCE SEQ_CAL_ID;
DROP SEQUENCE SEQ_EVT_ID;
DROP SEQUENCE SEQ_REZ_ID;
DROP SEQUENCE SEQ_AS_ID;

-- DML
-- READ
SELECT * FROM CALENDAR2 WHERE EMP_NO = 201 AND IS_DELETE = 'N';

SELECT * FROM EVENT2 WHERE CAL_NO = 1 AND IS_DELETE = 'N';

SELECT * FROM RESERVATION2 WHERE AS_NO = 1 AND IS_DELETE = 'N';

SELECT * FROM ASSET2 WHERE IS_DELETE = 'N';

-- CREATE
INSERT INTO CALENDAR2 VALUES (SEQ_CAL_ID.NEXTVAL, '기본캘린더', 'BLUE', DEFAULT, DEFAULT, 201);
INSERT INTO CALENDAR2 VALUES (SEQ_CAL_ID.NEXTVAL, '테스트캘린더', 'BLUE', DEFAULT, DEFAULT, 201);

INSERT INTO EVENT2 VALUES (SEQ_EVT_ID.NEXTVAL, '이벤트1', SYSDATE, SYSDATE + 1, DEFAULT, 1, NULL);
INSERT INTO EVENT2 VALUES (SEQ_EVT_ID.NEXTVAL, '이벤트2', SYSDATE, SYSDATE + 2, DEFAULT, 1, NULL);
INSERT INTO EVENT2 VALUES (SEQ_EVT_ID.NEXTVAL, '이벤트3', SYSDATE, SYSDATE + 3, DEFAULT, 1, NULL);

INSERT INTO ASSET2 VALUES (SEQ_AS_ID.NEXTVAL, '회의실1', 'BLUE', DEFAULT);
INSERT INTO ASSET2 VALUES (SEQ_AS_ID.NEXTVAL, '회의실2', 'GREEN', DEFAULT);
INSERT INTO ASSET2 VALUES (SEQ_AS_ID.NEXTVAL, '회의실3', 'YELLOW', DEFAULT);

INSERT INTO RESERVATION2 VALUES (SEQ_REZ_ID.NEXTVAL, '예약1', SYSDATE, SYSDATE + 1, DEFAULT, 1, NULL);
INSERT INTO RESERVATION2 VALUES (SEQ_REZ_ID.NEXTVAL, '예약2', SYSDATE, SYSDATE + 2, DEFAULT, 1, NULL);
INSERT INTO RESERVATION2 VALUES (SEQ_REZ_ID.NEXTVAL, '예약3', SYSDATE, SYSDATE + 3, DEFAULT, 2, NULL);
INSERT INTO RESERVATION2 VALUES (SEQ_REZ_ID.NEXTVAL, '예약4', SYSDATE, SYSDATE + 4, DEFAULT, 2, NULL);
INSERT INTO RESERVATION2 VALUES (SEQ_REZ_ID.NEXTVAL, '예약5', SYSDATE, SYSDATE + 5, DEFAULT, 3, NULL);

-- DELETE
UPDATE CALENDAR2 SET IS_DELETE = 'Y' WHERE CAL_NO = 2;

UPDATE EVENT2 SET IS_DELETE = 'Y' WHERE EVT_NO = 2;

UPDATE ASSET2 SET IS_DELETE = 'Y' WHERE AS_NO = 2;

UPDATE RESERVATION2 SET IS_DELETE = 'Y' WHERE REZ_NO = 2;

-- UPDATE
UPDATE CALENDAR2 SET 
NAME = '이름2',
COLOR = 'ORANGE',
STATUS = 'N'
WHERE CAL_NO = 2;

UPDATE EVENT2 SET 
NAME = '이름2',
START_DATE = SYSDATE + 1,
END_DATE = SYSDATE + 2
WHERE EVT_NO = 2;

UPDATE ASSET2 SET 
NAME = '이름2',
COLOR = 'ORANGE'
WHERE AS_NO = 2;

UPDATE RESERVATION2 SET
NAME = '이름2',
START_DATE = SYSDATE + 1,
END_DATE = SYSDATE + 2
WHERE REZ_NO = 2;